title : Miléna
description : student at Centrale supelec
theme : jekyll-theme-chirpy

# For a User/Organization site (username.github.io), keep it as ''.
# For a Project site (username.github.io/project), set it to '/project'[reference:3].
baseurl: ''

# The full protocol and hostname of your site.
# e.g., 'https://username.github.io' or your custom domain[reference:4][reference:5]
url: 'https://milenacdg.github.io'
lang: en
timezone: ''

tagline: test tagline

